package me.ilker.dota2compose.model.network.response

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import me.ilker.dota2compose.model.domain.Hero

@Serializable
data class HeroResponse(
    @SerialName("agi_gain") val agiGain: Double? = null,
    @SerialName("attack_range") val attackRange: Int? = null,
    @SerialName("attack_rate") val attackRate: Double? = null,
    @SerialName("attack_type") val attackType: String? = null,
    @SerialName("base_agi") val baseAgi: Int? = null,
    @SerialName("base_armor") val baseArmor: Double? = null,
    @SerialName("base_attack_max") val baseAttackMax: Int? = null,
    @SerialName("base_attack_min") val baseAttackMin: Int? = null,
    @SerialName("base_health") val baseHealth: Int? = null,
    @SerialName("base_health_regen") val baseHealthRegen: Double? = null,
    @SerialName("base_int") val baseInt: Int? = null,
    @SerialName("base_mana") val baseMana: Int? = null,
    @SerialName("base_mana_regen") val baseManaRegen: Double? = null,
    @SerialName("base_mr") val baseMr: Int? = null,
    @SerialName("base_str") val baseStr: Int? = null,
    @SerialName("cm_enabled") val cmEnabled: Boolean? = null,
    @SerialName("hero_id") val heroId: Int? = null,
    @SerialName("icon") val icon: String? = null,
    @SerialName("id") val id: Int? = null,
    @SerialName("img") val img: String? = null,
    @SerialName("int_gain") val intGain: Double? = null,
    @SerialName("legs") val legs: Int? = null,
    @SerialName("localized_name") val localizedName: String? = null,
    @SerialName("move_speed") val moveSpeed: Int? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("null_pick") val nullPick: Int? = null,
    @SerialName("null_win") val nullWin: Int? = null,
    @SerialName("1_pick") val pick1: Int? = null,
    @SerialName("2_pick") val pick2: Int? = null,
    @SerialName("3_pick") val pick3: Int? = null,
    @SerialName("4_pick") val pick4: Int? = null,
    @SerialName("5_pick") val pick5: Int? = null,
    @SerialName("6_pick") val pick6: Int? = null,
    @SerialName("7_pick") val pick7: Int? = null,
    @SerialName("8_pick") val pick8: Int? = null,
    @SerialName("primary_attr") val primaryAttr: String? = null,
    @SerialName("pro_ban") val proBan: Int? = null,
    @SerialName("pro_pick") val proPick: Int? = null,
    @SerialName("pro_win") val proWin: Int? = null,
    @SerialName("projectile_speed") val projectileSpeed: Int? = null,
    @SerialName("roles") val roles: List<String>? = null,
    @SerialName("str_gain") val strGain: Double? = null,
    @SerialName("turbo_picks") val turboPicks: Int? = null,
    @SerialName("turbo_wins") val turboWins: Int? = null,
    @SerialName("turn_rate") val turnRate: Double? = null,
    @SerialName("1_win") val win1: Int? = null,
    @SerialName("2_win") val win2: Int? = null,
    @SerialName("3_win") val win3: Int? = null,
    @SerialName("4_win") val win4: Int? = null,
    @SerialName("5_win") val win5: Int? = null,
    @SerialName("6_win") val win6: Int? = null,
    @SerialName("7_win") val win7: Int? = null,
    @SerialName("8_win") val win8: Int? = null
) {
    fun toDomain(): Hero = Hero(
        attackType = attackType,
        baseAgi = baseAgi,
        baseArmor = baseArmor,
        baseAttackMax = baseAttackMax,
        baseAttackMin = baseAttackMin,
        baseHealth = baseHealth,
        baseInt = baseInt,
        baseMana = baseMana,
        baseMr = baseMr,
        baseStr = baseStr,
        cmEnabled = cmEnabled,
        heroId = heroId,
        icon = icon,
        id = id,
        img = img,
        legs = legs,
        localizedName = localizedName,
        moveSpeed = moveSpeed,
        name = name,
        primaryAttr = primaryAttr,
        projectileSpeed = projectileSpeed,
        roles = roles
    )
}
