package me.ilker.dota2compose.domain

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Hero(
    @SerialName("agi_gain") val agiGain: Double,
    @SerialName("attack_range") val attackRange: Int,
    @SerialName("attack_rate") val attackRate: Double,
    @SerialName("attack_type") val attackType: String,
    @SerialName("base_agi") val baseAgi: Int,
    @SerialName("base_armor") val baseArmor: Double,
    @SerialName("base_attack_max") val baseAttackMax: Int,
    @SerialName("base_attack_min") val baseAttackMin: Int,
    @SerialName("base_health") val baseHealth: Int,
    @SerialName("base_health_regen") val baseHealthRegen: Double?,
    @SerialName("base_int") val baseInt: Int,
    @SerialName("base_mana") val baseMana: Int,
    @SerialName("base_mana_regen") val baseManaRegen: Double,
    @SerialName("base_mr") val baseMr: Int,
    @SerialName("base_str") val baseStr: Int,
    @SerialName("cm_enabled") val cmEnabled: Boolean,
    @SerialName("hero_id") val heroId: Int,
    @SerialName("icon") val icon: String,
    @SerialName("id") val id: Int,
    @SerialName("img") val img: String,
    @SerialName("int_gain") val intGain: Double,
    @SerialName("legs") val legs: Int,
    @SerialName("localized_name") val localizedName: String,
    @SerialName("move_speed") val moveSpeed: Int,
    @SerialName("name") val name: String,
    @SerialName("null_pick") val nullPick: Int,
    @SerialName("1_pick") val firstPick: Int,
    @SerialName("2_pick") val secondPick: Int,
    @SerialName("3_pick") val thirdPick: Int,
    @SerialName("4_pick") val fourthPick: Int,
    @SerialName("5_pick") val fifthPick: Int,
    @SerialName("6_pick") val sixthPick: Int,
    @SerialName("7_pick") val seventhPick: Int,
    @SerialName("8_pick") val eighthPick: Int,
    @SerialName("primary_attr") val primaryAttr: String,
    @SerialName("projectile_speed") val projectileSpeed: Int,
    @SerialName("roles") val roles: List<String>,
    @SerialName("str_gain") val strGain: Double,
    @SerialName("turbo_picks") val turboPicks: Int,
    @SerialName("turbo_wins") val turboWins: Int,
    @SerialName("turn_rate") val turnRate: Double,
    @SerialName("1_win") val firstPickWins: Int,
    @SerialName("2_win") val secondPickWins: Int,
    @SerialName("3_win") val thirdPickWins: Int,
    @SerialName("4_win") val fourthPickWins: Int,
    @SerialName("5_win") val fifthPickWins: Int,
    @SerialName("6_win") val sixthPickWins: Int,
    @SerialName("7_win") val seventhPickWins: Int,
    @SerialName("8_win") val eighthPickWins: Int
)
