[versions]
gradleplugin = "8.9.1"
kotlin = "2.1.20"
okhttp = "4.12.0"
hilt = "2.56.1"
compose = "2025.04.00"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.16.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.10.1"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.7"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
coil-compose = "io.coil-kt:coil-compose:2.7.0"

android-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
android-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
android-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref="okhttp"}
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref="okhttp"}

rxkotlin = "io.reactivex.rxjava3:rxkotlin:3.0.1"
retrofit = "com.squareup.retrofit2:retrofit:2.11.0"
retrofit2-kotlinx-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1"

junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.2.1"
androidx-espresso = "androidx.test.espresso:espresso-core:3.6.1"

[bundles]
okhttp = ["okhttp", "okhttp-logging-interceptor"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }